### ISSUE TITLE
Caching of Map Tiles

### ISSUE THREAD

**Issue by timwaters** [wikimaps-dev/mapwarper#4]
Map tiles need to be cached for performance improvement. Currently map tiles are served dynamically. Caching and detaching is important and needed.

This is the main story for the following tasks
- [x] #5 Investigate caching strategies
- [x] #6 Implement basic caching for unwarped maps
  backlog:
- [x] #34 Production ready map caching of rectified maps

**Comment by timwaters** [comment]
Passenger has tubocache which we could leverage for caching unwarped maps in the interim

**Comment by timwaters** [comment]
see https://blog.phusion.nl/2015/02/09/turbocaching-security-changes/ for more info

**Comment by timwaters** [comment]
added caching for unwarped maps, using passenger's turbo cache (and browser cache)
by using https cache header

**Comment by timwaters** [comment]
For rectified maps and layers which need to be decached upon a rectify and a crop etc, we have installed Redis and are using this to as an action cache to cache WMS and Tiles.

This should improve the WMS and Tile performances. If the cache is full, redis will expire the older tiles first.

Currently the server has around 1G set for this cache, will monitor and increase if possible.
